### ISSUE TITLE
App icon.

### ISSUE THREAD

**Issue by Toni-d-e-v** [Marionette-Software/user-app#1]
Hi, could you please tell me what is the name of logo used for icons on mobile, and webapp.
I would like to know, path or where in code is it specified so it can be changed.

![image](https://github.com/Marionette-Software/user-app/assets/62844491/e21fc39d-24b8-4a89-b047-9594a09071f1)
![image](https://github.com/Marionette-Software/user-app/assets/62844491/16d5452d-816e-479f-9acb-a4a705f53b56)

Thank you

**Comment by MaaTvII** [comment]
For Mobile

If you wish to change the logo for your app, locate the logo file at the following directory: /Users/mac/Desktop/user_app/assets/launcher.

Next, use the flutter_launcher_icons package by running the command 'flutter pub run flutter_launcher_icons'.

For web 

change icon and name:
/Users/mac/Desktop/user_app/web/index.html
/Users/mac/Desktop/user_app/web/icons
Favicon : /Users/mac/Desktop/user_app/web/favicon.ico
Name:/Users/mac/Desktop/user_app/lib/presentation/constants/app_info.dart

**Comment by Toni-d-e-v** [comment]
Thanks
